model:
  save_val_output: true
  gaussian:
    init_args:
      sh_degree: 3
  mlp_cfg:
    use: true
  log_cfg:
    log: true
    step: 50
  renderer:
    class_path: internal.renderers.ciga_renderer2.CigaRenderer
  save_val_metrics: true
  max_save_val_output: 10
  renderer_output_types: null
trainer:
  check_val_every_n_epoch: 1
  max_steps: 1000

data:
  path: /home/jinholee/Ciga/data/dataset/SF/traina20g1.8
  parser:
    class_path: EstimatedDepthBlockColmap
    init_args:
      down_sample_factor: 1.0
