model:
  initialize_from: outputs/UC_YCH_1018/checkpoints/epoch=43-step=30000.ckpt

data:
  path: /home/jinholee/Ciga/data/dataset/SF/traina20g1.8
  parser:
    class_path: EstimatedDepthBlockColmap
    init_args:
      block_dim: [200, 200]      
      content_threshold: 0.08    
      aabb: [-1000.0, -1000.0, 1000.0, 1000.0] 
